site_name: Yzl
repo_url: https://github.com/queil/yzl
site_url: https://queil.github.io/yzl
nav:
- Home: index.md
- API Reference: reference/index.md
- Contributing: contributing.md
theme: 
  name: material
  palette:
    primary: teal
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
