// Auto-generated by Yzl.Bindings.Gen - do not edit manually.
// Source schema: https://raw.githubusercontent.com/SchemaStore/schemastore/62b011a46804890a529efa2eba449be301f57bf3/src/schemas/json/kustomization.json
namespace rec Yzl.Bindings.Kustomize
open Yzl.Core

/// Represents a variable whose value will be sourced from a field in a Kubernetes object.
type Var() =
  /// Refers to a Kubernetes resource under the purview of this kustomization
  static member objref (value: NamedNode list)  = Yzl.map(value, "objref")
  /// Value of identifier name e.g. FOO used in container args, annotations, Appears in pod template as $(FOO)
  static member name (value: string)  = Yzl.str(value, "name")
  /// Value of identifier name e.g. FOO used in container args, annotations, Appears in pod template as $(FOO)
  static member name (value: Str)  = Yzl.str(value, "name")
  /// Refers to the field of the object referred to by objref whose value will be extracted for use in replacing $(FOO)
  static member fieldref (value: NamedNode list)  = Yzl.map(value, "fieldref")
  static member Default = Var()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Target() =
  static member version (value: string)  = Yzl.str(value, "version")
  static member version (value: Str)  = Yzl.str(value, "version")
  /// UNDOCUMENTED.
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// UNDOCUMENTED.
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member kind (value: string)  = Yzl.str(value, "kind")
  static member kind (value: Str)  = Yzl.str(value, "kind")
  static member group (value: string)  = Yzl.str(value, "group")
  static member group (value: Str)  = Yzl.str(value, "group")
  static member apiVersion (value: string)  = Yzl.str(value, "apiVersion")
  static member apiVersion (value: Str)  = Yzl.str(value, "apiVersion")
  static member Default = Target()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Selector specifies a set of resources. Any resource that matches intersection of all conditions is included in this set.
type Selector() =
  /// LabelSelector is a string that follows the label selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
  static member labelSelector (value: string)  = Yzl.str(value, "labelSelector")
  /// LabelSelector is a string that follows the label selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
  static member labelSelector (value: Str)  = Yzl.str(value, "labelSelector")
  /// AnnotationSelector is a string that follows the label selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
  static member annotationSelector (value: string)  = Yzl.str(value, "annotationSelector")
  /// AnnotationSelector is a string that follows the label selection expression https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
  static member annotationSelector (value: Str)  = Yzl.str(value, "annotationSelector")
  /// The version of the referent
  static member version (value: string)  = Yzl.str(value, "version")
  /// The version of the referent
  static member version (value: Str)  = Yzl.str(value, "version")
  /// The namespace of the referent
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// The namespace of the referent
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  /// The name of the referent
  static member name (value: string)  = Yzl.str(value, "name")
  /// The name of the referent
  static member name (value: Str)  = Yzl.str(value, "name")
  /// The kind of the referent
  static member kind (value: string)  = Yzl.str(value, "kind")
  /// The kind of the referent
  static member kind (value: Str)  = Yzl.str(value, "kind")
  /// The group of the referent
  static member group (value: string)  = Yzl.str(value, "group")
  /// The group of the referent
  static member group (value: Str)  = Yzl.str(value, "group")
  static member Default = Selector()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// SecretArgs contains the metadata of how to generate a secret
type SecretArgs() =
  /// Type of the secret, optional
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  /// Type of the secret, optional
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  /// Namespace for the secret, optional
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// Namespace for the secret, optional
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  /// Name - actually the partial name - of the generated resource
  static member name (value: string)  = Yzl.str(value, "name")
  /// Name - actually the partial name - of the generated resource
  static member name (value: Str)  = Yzl.str(value, "name")
  static member literals (value: string list)  = Yzl.seq(value, "literals")
  static member files (value: string list)  = Yzl.seq(value, "files")
  static member envs (value: string list)  = Yzl.seq(value, "envs")
  static member env (value: string)  = Yzl.str(value, "env")
  static member env (value: Str)  = Yzl.str(value, "env")
  static member behavior (value: string)  = Yzl.str(value, "behavior")
  static member KVSources (value: NamedNode list list)  = Yzl.seq(value, "KVSources")
  static member Default = SecretArgs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Replicas() =
  static member count (value: float)  = Yzl.float(value, "count")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member Default = Replicas()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ReplacementsTarget() =
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  /// The structured path(s) to the target nodes
  static member fieldPaths (value: string list)  = Yzl.seq(value, "fieldPaths")
  /// Exclude objects that match this
  static member reject (value: NamedNode list list)  = Yzl.seq(value, "reject")
  /// Include objects that match this
  static member select (value: NamedNode list)  = Yzl.map(value, "select")
  static member Default = ReplacementsTarget()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// The source of the value
type ReplacementsSource() =
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  /// The structured path to the source value
  static member fieldPath (value: string)  = Yzl.str(value, "fieldPath")
  /// The structured path to the source value
  static member fieldPath (value: Str)  = Yzl.str(value, "fieldPath")
  /// The namespace of the referent
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// The namespace of the referent
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  /// The name of the referent
  static member name (value: string)  = Yzl.str(value, "name")
  /// The name of the referent
  static member name (value: Str)  = Yzl.str(value, "name")
  /// The kind of the referent
  static member kind (value: string)  = Yzl.str(value, "kind")
  /// The kind of the referent
  static member kind (value: Str)  = Yzl.str(value, "kind")
  /// The version of the referent
  static member version (value: string)  = Yzl.str(value, "version")
  /// The version of the referent
  static member version (value: Str)  = Yzl.str(value, "version")
  /// The group of the referent
  static member group (value: string)  = Yzl.str(value, "group")
  /// The group of the referent
  static member group (value: Str)  = Yzl.str(value, "group")
  static member Default = ReplacementsSource()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ReplacementsPath() =
  static member path (value: string)  = Yzl.str(value, "path")
  static member path (value: Str)  = Yzl.str(value, "path")
  static member Default = ReplacementsPath()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ReplacementsInline() =
  static member Default = ReplacementsInline()
  static member yzl (build:NamedNode list) : Node = build |> lift
type PatchesInlinePatch() =
  /// Refers to a Kubernetes object that the patch will be applied to. It must refer to a Kubernetes resource under the purview of this kustomization
  static member target (value: NamedNode list)  = Yzl.map(value, "target")
  static member patch (value: string)  = Yzl.str(value, "patch")
  static member patch (value: Str)  = Yzl.str(value, "patch")
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  static member Default = PatchesInlinePatch()
  static member yzl (build:NamedNode list) : Node = build |> lift
type PatchesPatchPath() =
  /// Refers to a Kubernetes object that the patch will be applied to. It must refer to a Kubernetes resource under the purview of this kustomization
  static member target (value: NamedNode list)  = Yzl.map(value, "target")
  static member path (value: string)  = Yzl.str(value, "path")
  static member path (value: Str)  = Yzl.str(value, "path")
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  static member Default = PatchesPatchPath()
  static member yzl (build:NamedNode list) : Node = build |> lift
type PatchesOptions() =
  static member allowKindChange (value: bool)  = Yzl.boolean(value, "allowKindChange")
  static member allowNameChange (value: bool)  = Yzl.boolean(value, "allowNameChange")
  static member Default = PatchesOptions()
  static member yzl (build:NamedNode list) : Node = build |> lift
type PatchTarget() =
  static member version (value: string)  = Yzl.str(value, "version")
  static member version (value: Str)  = Yzl.str(value, "version")
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member kind (value: string)  = Yzl.str(value, "kind")
  static member kind (value: Str)  = Yzl.str(value, "kind")
  static member group (value: string)  = Yzl.str(value, "group")
  static member group (value: Str)  = Yzl.str(value, "group")
  static member Default = PatchTarget()
  static member yzl (build:NamedNode list) : Node = build |> lift
type PatchJson6902() =
  static member Default = PatchJson6902()
  static member yzl (build:NamedNode list) : Node = build |> lift
type NameArgs() =
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member Default = NameArgs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Metadata() =
  static member annotations (value: NamedNode list)  = Yzl.map(value, "annotations")
  static member labels (value: NamedNode list)  = Yzl.map(value, "labels")
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member Default = Metadata()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Labels() =
  /// FieldSpec completely specifies a kustomizable field in a k8s API object. It helps define the operands of transformations
  static member fields (value: NamedNode list list)  = Yzl.seq(value, "fields")
  /// IncludeTemplates indicates should transformer include the template labels
  static member includeTemplates (value: bool)  = Yzl.boolean(value, "includeTemplates")
  /// IncludeSelectors indicates should transformer include the fieldSpecs for selectors
  static member includeSelectors (value: bool)  = Yzl.boolean(value, "includeSelectors")
  /// Pairs contains the key-value pairs for labels to add
  static member pairs (value: NamedNode list)  = Yzl.map(value, "pairs")
  static member Default = Labels()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Kustomization() =
  /// Allows things modified by kustomize to be injected into a container specification. A var is a name (e.g. FOO) associated with a field in a specific resource instance.  The field must contain a value of type string, and defaults to the name field of the instance
  static member vars (value: NamedNode list list)  = Yzl.seq(value, "vars")
  /// Validators is a list of files containing validators
  static member validators (value: string list)  = Yzl.seq(value, "validators")
  /// Transformers is a list of files containing transformers
  static member transformers (value: string list)  = Yzl.seq(value, "transformers")
  /// sortOptions is used to sort the resources kustomize outputs
  static member sortOptions (value: Node)  = Yzl.named(value, "sortOptions")
  /// SecretGenerator is a list of secrets to generate from local data (one secret per list item)
  static member secretGenerator (value: NamedNode list list)  = Yzl.seq(value, "secretGenerator")
  /// Components are relative paths or git repository URLs specifying a directory containing a kustomization.yaml file of Kind Component.
  static member components (value: string list)  = Yzl.seq(value, "components")
  /// Resources specifies relative paths to files holding YAML representations of kubernetes API objects. URLs and globs not supported.
  static member resources (value: string list)  = Yzl.seq(value, "resources")
  /// Replicas is a list of (resource name, count) for changing number of replicas for a resources. It will match any group and kind that has a matching name and that is one of: Deployment, ReplicationController, Replicaset, Statefulset.
  static member replicas (value: NamedNode list list)  = Yzl.seq(value, "replicas")
  ///  PatchesStrategicMerge specifies the relative path to a file containing a strategic merge patch. URLs and globs are not supported
  static member patchesStrategicMerge (value: string list)  = Yzl.seq(value, "patchesStrategicMerge")
  /// JSONPatches is a list of JSONPatch for applying JSON patch. See http://jsonpatch.com
  static member patchesJson6902 (value: NamedNode list list)  = Yzl.seq(value, "patchesJson6902")
  /// Apply a patch to multiple resources
  static member patches (value: Node list)  = Yzl.seq(value, "patches")
  /// OpenAPI contains information about what kubernetes schema to use
  static member openapi (value: NamedNode list)  = Yzl.map(value, "openapi")
  /// Substitute field(s) in N target(s) with a field from a source
  static member replacements (value: Node list)  = Yzl.seq(value, "replacements")
  /// Namespace to add to all objects
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// Namespace to add to all objects
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  /// NameSuffix will suffix the names of all resources mentioned in the kustomization file including generated configmaps and secrets
  static member nameSuffix (value: string)  = Yzl.str(value, "nameSuffix")
  /// NameSuffix will suffix the names of all resources mentioned in the kustomization file including generated configmaps and secrets
  static member nameSuffix (value: Str)  = Yzl.str(value, "nameSuffix")
  /// NamePrefix will prefix the names of all resources mentioned in the kustomization file including generated configmaps and secrets
  static member namePrefix (value: string)  = Yzl.str(value, "namePrefix")
  /// NamePrefix will prefix the names of all resources mentioned in the kustomization file including generated configmaps and secrets
  static member namePrefix (value: Str)  = Yzl.str(value, "namePrefix")
  /// Contains metadata about a Resource
  static member metadata (value: NamedNode list)  = Yzl.map(value, "metadata")
  static member kind (value: string)  = Yzl.str(value, "kind")
  static member kind (value: Str)  = Yzl.str(value, "kind")
  /// Labels to add to all objects but not selectors
  static member labels (value: NamedNode list list)  = Yzl.seq(value, "labels")
  static member inventory (value: NamedNode list)  = Yzl.map(value, "inventory")
  /// Images is a list of (image name, new name, new tag or digest) for changing image names, tags or digests. This can also be achieved with a patch, but this operator is simpler to specify.
  static member images (value: NamedNode list list)  = Yzl.seq(value, "images")
  /// HelmGlobals contains helm configuration that isn't chart specific
  static member helmGlobals (value: NamedNode list)  = Yzl.map(value, "helmGlobals")
  /// HelmCharts is a list of helm chart configuration instances
  static member helmCharts (value: NamedNode list list)  = Yzl.seq(value, "helmCharts")
  /// Generators is a list of files containing custom generators
  static member generators (value: string list)  = Yzl.seq(value, "generators")
  static member generatorOptions (value: NamedNode list)  = Yzl.map(value, "generatorOptions")
  /// Crds specifies relative paths to Custom Resource Definition files. This allows custom resources to be recognized as operands, making it possible to add them to the Resources list. CRDs themselves are not modified.
  static member crds (value: string list)  = Yzl.seq(value, "crds")
  /// Configurations is a list of transformer configuration files
  static member configurations (value: string list)  = Yzl.seq(value, "configurations")
  /// ConfigMapGenerator is a list of configmaps to generate from local data (one configMap per list item)
  static member configMapGenerator (value: NamedNode list list)  = Yzl.seq(value, "configMapGenerator")
  ///  CommonLabels to add to all objects and selectors
  static member commonLabels (value: NamedNode list)  = Yzl.map(value, "commonLabels")
  /// BuildMetadata is a list of strings used to toggle different build options
  static member buildMetadata (value: string list)  = Yzl.seq(value, "buildMetadata")
  /// CommonAnnotations to add to all objects
  static member commonAnnotations (value: NamedNode list)  = Yzl.map(value, "commonAnnotations")
  /// DEPRECATED. Bases are relative paths or git repository URLs specifying a directory containing a kustomization.yaml file.
  static member bases (value: string list)  = Yzl.seq(value, "bases")
  static member apiVersion (value: string)  = Yzl.str(value, "apiVersion")
  static member apiVersion (value: Str)  = Yzl.str(value, "apiVersion")
  static member Default = Kustomization()
  static member yzl (build:NamedNode list) : Node = build |> lift
type KVSource() =
  static member pluginType (value: string)  = Yzl.str(value, "pluginType")
  static member pluginType (value: Str)  = Yzl.str(value, "pluginType")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member args (value: string list)  = Yzl.seq(value, "args")
  static member Default = KVSource()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Inventory appends an object that contains the record of all other objects, which can be used in apply, prune and delete
type Inventory() =
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member configMap (value: NamedNode list)  = Yzl.map(value, "configMap")
  static member Default = Inventory()
  static member yzl (build:NamedNode list) : Node = build |> lift
type Image() =
  /// UNDOCUMENTED.
  static member tagSuffix (value: string)  = Yzl.str(value, "tagSuffix")
  /// UNDOCUMENTED.
  static member tagSuffix (value: Str)  = Yzl.str(value, "tagSuffix")
  static member newTag (value: string)  = Yzl.str(value, "newTag")
  static member newTag (value: Str)  = Yzl.str(value, "newTag")
  static member newName (value: string)  = Yzl.str(value, "newName")
  static member newName (value: Str)  = Yzl.str(value, "newName")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member digest (value: string)  = Yzl.str(value, "digest")
  static member digest (value: Str)  = Yzl.str(value, "digest")
  static member Default = Image()
  static member yzl (build:NamedNode list) : Node = build |> lift
type HelmChart() =
  static member nameTemplate (value: string)  = Yzl.str(value, "nameTemplate")
  static member nameTemplate (value: Str)  = Yzl.str(value, "nameTemplate")
  static member kubeVersion (value: string)  = Yzl.str(value, "kubeVersion")
  static member kubeVersion (value: Str)  = Yzl.str(value, "kubeVersion")
  static member apiVersions (value: string list)  = Yzl.seq(value, "apiVersions")
  static member skipTests (value: bool)  = Yzl.boolean(value, "skipTests")
  static member additionalValuesFiles (value: string list)  = Yzl.seq(value, "additionalValuesFiles")
  static member skipHooks (value: bool)  = Yzl.boolean(value, "skipHooks")
  static member includeCRDs (value: bool)  = Yzl.boolean(value, "includeCRDs")
  static member valuesMerge (value: string)  = Yzl.str(value, "valuesMerge")
  static member valuesMerge (value: Str)  = Yzl.str(value, "valuesMerge")
  static member valuesInline (value: NamedNode list)  = Yzl.map(value, "valuesInline")
  static member valuesFile (value: string)  = Yzl.str(value, "valuesFile")
  static member valuesFile (value: Str)  = Yzl.str(value, "valuesFile")
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member releaseName (value: string)  = Yzl.str(value, "releaseName")
  static member releaseName (value: Str)  = Yzl.str(value, "releaseName")
  static member repo (value: string)  = Yzl.str(value, "repo")
  static member repo (value: Str)  = Yzl.str(value, "repo")
  static member version (value: string)  = Yzl.str(value, "version")
  static member version (value: Str)  = Yzl.str(value, "version")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member Default = HelmChart()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// GeneratorOptions modify behavior of all ConfigMap and Secret generators
type GeneratorOptions() =
  /// Labels to add to all generated resources
  static member labels (value: NamedNode list)  = Yzl.map(value, "labels")
  /// Immutable if true add to all generated resources
  static member immutable (value: bool)  = Yzl.boolean(value, "immutable")
  /// DisableNameSuffixHash if true disables the default behavior of adding a suffix to the names of generated resources that is a hash of the resource contents
  static member disableNameSuffixHash (value: bool)  = Yzl.boolean(value, "disableNameSuffixHash")
  /// Annotations to add to all generated resources
  static member annotations (value: NamedNode list)  = Yzl.map(value, "annotations")
  static member Default = GeneratorOptions()
  static member yzl (build:NamedNode list) : Node = build |> lift
type FieldSpec() =
  static member version (value: string)  = Yzl.str(value, "version")
  static member version (value: Str)  = Yzl.str(value, "version")
  static member path (value: string)  = Yzl.str(value, "path")
  static member path (value: Str)  = Yzl.str(value, "path")
  static member kind (value: string)  = Yzl.str(value, "kind")
  static member kind (value: Str)  = Yzl.str(value, "kind")
  static member group (value: string)  = Yzl.str(value, "group")
  static member group (value: Str)  = Yzl.str(value, "group")
  static member create (value: bool)  = Yzl.boolean(value, "create")
  static member Default = FieldSpec()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Contains the fieldPath to an object field
type FieldSelector() =
  static member fieldpath (value: string)  = Yzl.str(value, "fieldpath")
  static member fieldpath (value: Str)  = Yzl.str(value, "fieldpath")
  static member Default = FieldSelector()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// ConfigMapArgs contains the metadata of how to generate a configmap
type ConfigMapArgs() =
  static member options (value: NamedNode list)  = Yzl.map(value, "options")
  /// Namespace for the configmap, optional
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  /// Namespace for the configmap, optional
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  /// Name - actually the partial name - of the generated resource
  static member name (value: string)  = Yzl.str(value, "name")
  /// Name - actually the partial name - of the generated resource
  static member name (value: Str)  = Yzl.str(value, "name")
  /// A list of literal pair sources. Each literal source should be a key and literal value, e.g. `key=value`
  static member literals (value: string list)  = Yzl.seq(value, "literals")
  /// A list of file sources to use in creating a list of key, value pairs
  static member files (value: string list)  = Yzl.seq(value, "files")
  /// A list of file paths. The contents of each file should be one key=value pair per line
  static member envs (value: string list)  = Yzl.seq(value, "envs")
  /// Deprecated.  Use envs instead.
  static member env (value: string)  = Yzl.str(value, "env")
  /// Deprecated.  Use envs instead.
  static member env (value: Str)  = Yzl.str(value, "env")
  static member behavior (value: string)  = Yzl.str(value, "behavior")
  static member KVSources (value: NamedNode list list)  = Yzl.seq(value, "KVSources")
  static member Default = ConfigMapArgs()
  static member yzl (build:NamedNode list) : Node = build |> lift

[<AutoOpen>]
module Builders =
  let objref value = Yzl.map(value, "objref")
  let inline name value = Yzl.str(value, "name")
  let fieldref value = Yzl.map(value, "fieldref")
  let inline version value = Yzl.str(value, "version")
  let inline ``namespace`` value = Yzl.str(value, "namespace")
  let inline kind value = Yzl.str(value, "kind")
  let inline group value = Yzl.str(value, "group")
  let inline apiVersion value = Yzl.str(value, "apiVersion")
  let inline labelSelector value = Yzl.str(value, "labelSelector")
  let inline annotationSelector value = Yzl.str(value, "annotationSelector")
  let inline ``type`` value = Yzl.str(value, "type")
  let inline literals value = Yzl.seq(value, "literals")
  let inline files value = Yzl.seq(value, "files")
  let inline envs value = Yzl.seq(value, "envs")
  let inline env value = Yzl.str(value, "env")
  let inline behavior value = Yzl.str(value, "behavior")
  let inline KVSources value = Yzl.seq(value, "KVSources")
  let count value = Yzl.float(value, "count")
  let inline fieldPaths value = Yzl.seq(value, "fieldPaths")
  let inline reject value = Yzl.seq(value, "reject")
  let select value = Yzl.map(value, "select")
  let inline fieldPath value = Yzl.str(value, "fieldPath")
  let inline path value = Yzl.str(value, "path")
  let target value = Yzl.map(value, "target")
  let inline patch value = Yzl.str(value, "patch")
  let allowKindChange value = Yzl.boolean(value, "allowKindChange")
  let allowNameChange value = Yzl.boolean(value, "allowNameChange")
  let annotations value = Yzl.map(value, "annotations")
  let inline fields value = Yzl.seq(value, "fields")
  let includeTemplates value = Yzl.boolean(value, "includeTemplates")
  let includeSelectors value = Yzl.boolean(value, "includeSelectors")
  let pairs value = Yzl.map(value, "pairs")
  let inline vars value = Yzl.seq(value, "vars")
  let inline validators value = Yzl.seq(value, "validators")
  let inline transformers value = Yzl.seq(value, "transformers")
  let sortOptions value = Yzl.named(value, "sortOptions")
  let inline secretGenerator value = Yzl.seq(value, "secretGenerator")
  let inline components value = Yzl.seq(value, "components")
  let inline resources value = Yzl.seq(value, "resources")
  let inline replicas value = Yzl.seq(value, "replicas")
  let inline patchesStrategicMerge value = Yzl.seq(value, "patchesStrategicMerge")
  let inline patchesJson6902 value = Yzl.seq(value, "patchesJson6902")
  let inline patches value = Yzl.seq(value, "patches")
  let openapi value = Yzl.map(value, "openapi")
  let inline replacements value = Yzl.seq(value, "replacements")
  let inline nameSuffix value = Yzl.str(value, "nameSuffix")
  let inline namePrefix value = Yzl.str(value, "namePrefix")
  let metadata value = Yzl.map(value, "metadata")
  let inventory value = Yzl.map(value, "inventory")
  let inline images value = Yzl.seq(value, "images")
  let helmGlobals value = Yzl.map(value, "helmGlobals")
  let inline helmCharts value = Yzl.seq(value, "helmCharts")
  let inline generators value = Yzl.seq(value, "generators")
  let generatorOptions value = Yzl.map(value, "generatorOptions")
  let inline crds value = Yzl.seq(value, "crds")
  let inline configurations value = Yzl.seq(value, "configurations")
  let inline configMapGenerator value = Yzl.seq(value, "configMapGenerator")
  let commonLabels value = Yzl.map(value, "commonLabels")
  let inline buildMetadata value = Yzl.seq(value, "buildMetadata")
  let commonAnnotations value = Yzl.map(value, "commonAnnotations")
  let inline bases value = Yzl.seq(value, "bases")
  let inline pluginType value = Yzl.str(value, "pluginType")
  let inline args value = Yzl.seq(value, "args")
  let configMap value = Yzl.map(value, "configMap")
  let inline tagSuffix value = Yzl.str(value, "tagSuffix")
  let inline newTag value = Yzl.str(value, "newTag")
  let inline newName value = Yzl.str(value, "newName")
  let inline digest value = Yzl.str(value, "digest")
  let inline nameTemplate value = Yzl.str(value, "nameTemplate")
  let inline kubeVersion value = Yzl.str(value, "kubeVersion")
  let inline apiVersions value = Yzl.seq(value, "apiVersions")
  let skipTests value = Yzl.boolean(value, "skipTests")
  let inline additionalValuesFiles value = Yzl.seq(value, "additionalValuesFiles")
  let skipHooks value = Yzl.boolean(value, "skipHooks")
  let includeCRDs value = Yzl.boolean(value, "includeCRDs")
  let inline valuesMerge value = Yzl.str(value, "valuesMerge")
  let valuesInline value = Yzl.map(value, "valuesInline")
  let inline valuesFile value = Yzl.str(value, "valuesFile")
  let inline releaseName value = Yzl.str(value, "releaseName")
  let inline repo value = Yzl.str(value, "repo")
  let immutable value = Yzl.boolean(value, "immutable")
  let disableNameSuffixHash value = Yzl.boolean(value, "disableNameSuffixHash")
  let create value = Yzl.boolean(value, "create")
  let inline fieldpath value = Yzl.str(value, "fieldpath")
