// Auto-generated by Yzl.Bindings.Gen - do not edit manually.
// Source schema: https://raw.githubusercontent.com/datreeio/CRDs-catalog/eb53ba0436c2577a9a9f0ece5f2a66ce2c48253f/bitnami.com/sealedsecret_v1alpha1.json
namespace rec Yzl.Bindings.SealedSecrets
open Yzl.Core

/// SealedSecret is the K8s representation of a "sealed Secret" - a regular k8s Secret that has been sealed (encrypted) using the controller's key.
type SealedSecret() =
  /// SealedSecretStatus is the most recently observed status of the SealedSecret.
  static member status (value: NamedNode list)  = Yzl.map(value, "status")
  /// SealedSecretSpec is the specification of a SealedSecret.
  static member spec (value: NamedNode list)  = Yzl.map(value, "spec")
  static member metadata (value: NamedNode list)  = Yzl.map(value, "metadata")
  /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  static member kind (value: string)  = Yzl.str(value, "kind")
  /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  static member kind (value: Str)  = Yzl.str(value, "kind")
  /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
  static member apiVersion (value: string)  = Yzl.str(value, "apiVersion")
  /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
  static member apiVersion (value: Str)  = Yzl.str(value, "apiVersion")
  static member Default = SealedSecret()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// SealedSecretStatus is the most recently observed status of the SealedSecret.
type status() =
  /// ObservedGeneration reflects the generation most recently observed by the sealed-secrets controller.
  static member observedGeneration (value: int)  = Yzl.int(value, "observedGeneration")
  /// Represents the latest available observations of a sealed secret's current state.
  static member conditions (value: NamedNode list list)  = Yzl.seq(value, "conditions")
  static member Default = status()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// SealedSecretSpec is the specification of a SealedSecret.
type spec() =
  /// Template defines the structure of the Secret that will be created from this sealed secret.
  static member template (value: NamedNode list)  = Yzl.map(value, "template")
  static member encryptedData (value: NamedNode list)  = Yzl.map(value, "encryptedData")
  /// Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
  static member data (value: string)  = Yzl.str(value, "data")
  /// Data is deprecated and will be removed eventually. Use per-value EncryptedData instead.
  static member data (value: Str)  = Yzl.str(value, "data")
  static member Default = spec()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Template defines the structure of the Secret that will be created from this sealed secret.
type template() =
  /// Used to facilitate programmatic handling of secret data.
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  /// Used to facilitate programmatic handling of secret data.
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  /// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
  static member metadata (value: NamedNode list)  = Yzl.map(value, "metadata")
  /// Immutable, if set to true, ensures that data stored in the Secret cannot be updated (only object metadata can be modified). If not set to true, the field can be modified at any time. Defaulted to nil.
  static member immutable (value: bool)  = Yzl.boolean(value, "immutable")
  /// Keys that should be templated using decrypted data.
  static member data (value: NamedNode list)  = Yzl.map(value, "data")
  static member Default = template()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
type metadata() =
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member labels (value: NamedNode list)  = Yzl.map(value, "labels")
  static member finalizers (value: string list)  = Yzl.seq(value, "finalizers")
  static member annotations (value: NamedNode list)  = Yzl.map(value, "annotations")
  static member Default = metadata()
  static member yzl (build:NamedNode list) : Node = build |> lift

type Builders() =
  static member status (value: NamedNode list)  = Yzl.map(value, "status")
  static member spec (value: NamedNode list)  = Yzl.map(value, "spec")
  static member metadata (value: NamedNode list)  = Yzl.map(value, "metadata")
  static member kind (value: string)  = Yzl.str(value, "kind")
  static member kind (value: Str)  = Yzl.str(value, "kind")
  static member apiVersion (value: string)  = Yzl.str(value, "apiVersion")
  static member apiVersion (value: Str)  = Yzl.str(value, "apiVersion")
  static member observedGeneration (value: int)  = Yzl.int(value, "observedGeneration")
  static member conditions (value: NamedNode list list)  = Yzl.seq(value, "conditions")
  static member template (value: NamedNode list)  = Yzl.map(value, "template")
  static member encryptedData (value: NamedNode list)  = Yzl.map(value, "encryptedData")
  static member data (value: string)  = Yzl.str(value, "data")
  static member data (value: Str)  = Yzl.str(value, "data")
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member immutable (value: bool)  = Yzl.boolean(value, "immutable")
  static member data (value: NamedNode list)  = Yzl.map(value, "data")
  static member ``namespace`` (value: string)  = Yzl.str(value, "namespace")
  static member ``namespace`` (value: Str)  = Yzl.str(value, "namespace")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member labels (value: NamedNode list)  = Yzl.map(value, "labels")
  static member finalizers (value: string list)  = Yzl.seq(value, "finalizers")
  static member annotations (value: NamedNode list)  = Yzl.map(value, "annotations")
