namespace rec Yzl.Bindings.GitlabCi
open Yzl.Core

/// Common tags
type Common() =
  static member ``when`` (value: string)  = Yzl.str(value, "when")
  static member ``when`` (value: Str)  = Yzl.str(value, "when")
  static member untracked (value: bool)  = Yzl.boolean(value, "untracked")
  static member paths (value: string list)  = Yzl.seq(value, "paths")
  static member Default = Common()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepExec() =
  /// WorkDir is the working directly in which `command` will be exec'ed.
  static member work_dir (value: string)  = Yzl.str(value, "work_dir")
  /// WorkDir is the working directly in which `command` will be exec'ed.
  static member work_dir (value: Str)  = Yzl.str(value, "work_dir")
  /// Command are the parameters to the system exec API. It does not invoke a shell.
  static member command (value: string list)  = Yzl.seq(value, "command")
  static member Default = stepExec()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// OCIReference is a reference to a step hosted in an OCI repository.
type stepOciReference() =
  static member oci (value: NamedNode list)  = Yzl.map(value, "oci")
  static member Default = stepOciReference()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// GitReference is a reference to a step in a Git repository.
type stepGitReference() =
  static member git (value: NamedNode list)  = Yzl.map(value, "git")
  static member Default = stepGitReference()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepNamedValues() =
  static member Default = stepNamedValues()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepNamedStrings() =
  static member Default = stepNamedStrings()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepName() =
  static member Default = stepName()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Any of these step use cases are valid.
type step() =
  static member Default = step()
  static member yzl (build:NamedNode list) : Node = build |> lift
type hooks() =
  static member pre_get_sources_script (value: NamedNode list)  = Yzl.map(value, "pre_get_sources_script")
  static member Default = hooks()
  static member yzl (build:NamedNode list) : Node = build |> lift
type tags() =
  static member Default = tags()
  static member yzl (build:NamedNode list) : Node = build |> lift
type job_template() =
  static member pages (value: Node)  = Yzl.named(value, "pages")
  /// Deprecated. Use `pages.publish` instead. A path to a directory that contains the files to be published with Pages.
  static member publish (value: string)  = Yzl.str(value, "publish")
  /// Deprecated. Use `pages.publish` instead. A path to a directory that contains the files to be published with Pages.
  static member publish (value: Str)  = Yzl.str(value, "publish")
  static member ``inherit`` (value: NamedNode list)  = Yzl.map(value, "inherit")
  static member trigger (value: Node)  = Yzl.named(value, "trigger")
  /// Limit job concurrency. Can be used to ensure that the Runner will not run certain jobs simultaneously.
  static member resource_group (value: string)  = Yzl.str(value, "resource_group")
  /// Limit job concurrency. Can be used to ensure that the Runner will not run certain jobs simultaneously.
  static member resource_group (value: Str)  = Yzl.str(value, "resource_group")
  static member interruptible (value: NamedNode list)  = Yzl.map(value, "interruptible")
  static member ``parallel`` (value: NamedNode list)  = Yzl.map(value, "parallel")
  static member retry (value: NamedNode list)  = Yzl.map(value, "retry")
  /// Must be a regular expression, optionally but recommended to be quoted, and must be surrounded with '/'. Example: '/Code coverage: \d+\.\d+/'
  static member coverage (value: string)  = Yzl.str(value, "coverage")
  /// Must be a regular expression, optionally but recommended to be quoted, and must be surrounded with '/'. Example: '/Code coverage: \d+\.\d+/'
  static member coverage (value: Str)  = Yzl.str(value, "coverage")
  /// Indicates that the job creates a Release.
  static member release (value: NamedNode list)  = Yzl.map(value, "release")
  /// Used to associate environment metadata with a deploy. Environment can have a name and URL attached to it, and will be displayed under /environments under the project.
  static member environment (value: Node)  = Yzl.named(value, "environment")
  static member artifacts (value: NamedNode list)  = Yzl.map(value, "artifacts")
  /// Specify a list of job names from earlier stages from which artifacts should be loaded. By default, all previous artifacts are passed. Use an empty array to skip downloading artifacts.
  static member dependencies (value: string list)  = Yzl.seq(value, "dependencies")
  static member manual_confirmation (value: string)  = Yzl.str(value, "manual_confirmation")
  static member manual_confirmation (value: Str)  = Yzl.str(value, "manual_confirmation")
  static member start_in (value: NamedNode list)  = Yzl.map(value, "start_in")
  static member ``when`` (value: NamedNode list)  = Yzl.map(value, "when")
  static member timeout (value: NamedNode list)  = Yzl.map(value, "timeout")
  static member allow_failure (value: NamedNode list)  = Yzl.map(value, "allow_failure")
  static member tags (value: NamedNode list)  = Yzl.map(value, "tags")
  /// Job will run *except* for when these filtering options match.
  static member except (value: NamedNode list)  = Yzl.map(value, "except")
  /// The list of jobs in previous stages whose sole completion is needed to start the current job.
  static member needs (value: Node list)  = Yzl.seq(value, "needs")
  /// The name of one or more jobs to inherit configuration from.
  static member extends (value: Node)  = Yzl.named(value, "extends")
  /// Job will run *only* when these filtering options match.
  static member only (value: NamedNode list)  = Yzl.map(value, "only")
  /// Define what stage the job will run in.
  static member stage (value: Node)  = Yzl.named(value, "stage")
  static member run (value: NamedNode list)  = Yzl.map(value, "run")
  static member script (value: NamedNode list)  = Yzl.map(value, "script")
  static member secrets (value: NamedNode list)  = Yzl.map(value, "secrets")
  static member inputs (value: NamedNode list)  = Yzl.map(value, "inputs")
  static member identity (value: NamedNode list)  = Yzl.map(value, "identity")
  static member id_tokens (value: NamedNode list)  = Yzl.map(value, "id_tokens")
  static member cache (value: NamedNode list)  = Yzl.map(value, "cache")
  static member variables (value: NamedNode list)  = Yzl.map(value, "variables")
  static member rules (value: NamedNode list)  = Yzl.map(value, "rules")
  static member hooks (value: NamedNode list)  = Yzl.map(value, "hooks")
  static member after_script (value: NamedNode list)  = Yzl.map(value, "after_script")
  static member before_script (value: NamedNode list)  = Yzl.map(value, "before_script")
  static member services (value: NamedNode list)  = Yzl.map(value, "services")
  static member image (value: NamedNode list)  = Yzl.map(value, "image")
  static member Default = job_template()
  static member yzl (build:NamedNode list) : Node = build |> lift
type job() =
  static member Default = job()
  static member yzl (build:NamedNode list) : Node = build |> lift
type inputs() =
  static member Default = inputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type interruptible() =
  static member Default = interruptible()
  static member yzl (build:NamedNode list) : Node = build |> lift
type retry_errors() =
  static member Default = retry_errors()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// The number of times the job will be retried if it fails. Defaults to 0 and can max be retried 2 times (3 times total).
type retry_max() =
  static member Default = retry_max()
  static member yzl (build:NamedNode list) : Node = build |> lift
type retry() =
  static member Default = retry()
  static member yzl (build:NamedNode list) : Node = build |> lift
type filter() =
  static member Default = filter()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Filter job by different keywords that determine origin or state, or by supplying string/regex to check against branch/tag names.
type filter_refs() =
  static member Default = filter_refs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type cache_item() =
  static member fallback_keys (value: string list)  = Yzl.seq(value, "fallback_keys")
  static member unprotect (value: bool)  = Yzl.boolean(value, "unprotect")
  static member policy (value: string)  = Yzl.str(value, "policy")
  static member policy (value: Str)  = Yzl.str(value, "policy")
  static member key (value: Node)  = Yzl.named(value, "key")
  static member Default = cache_item()
  static member yzl (build:NamedNode list) : Node = build |> lift
type cache() =
  static member Default = cache()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ``when``() =
  static member Default = ``when``()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Use the `needs:parallel:matrix` keyword to specify parallelized jobs needed to be completed for the job to run. [Learn More](https://docs.gitlab.com/ci/yaml/#needsparallelmatrix)
type parallel_matrix() =
  static member Default = parallel_matrix()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Splits up a single job into multiple that run in parallel. Provides `CI_NODE_INDEX` and `CI_NODE_TOTAL` environment variables to the jobs.
type ``parallel``() =
  static member Default = ``parallel``()
  static member yzl (build:NamedNode list) : Node = build |> lift
type allow_failure() =
  static member Default = allow_failure()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rulesNeeds() =
  static member Default = rulesNeeds()
  static member yzl (build:NamedNode list) : Node = build |> lift
type start_in() =
  static member Default = start_in()
  static member yzl (build:NamedNode list) : Node = build |> lift
type timeout() =
  static member Default = timeout()
  static member yzl (build:NamedNode list) : Node = build |> lift
type exists() =
  static member Default = exists()
  static member yzl (build:NamedNode list) : Node = build |> lift
type changes() =
  static member Default = changes()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ``if``() =
  static member Default = ``if``()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rulesVariables() =
  static member Default = rulesVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
type jobVariables() =
  static member Default = jobVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
type globalVariables() =
  static member Default = globalVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Define the rules for when pipeline should be automatically cancelled.
type workflowAutoCancel() =
  static member on_new_commit (value: string)  = Yzl.str(value, "on_new_commit")
  static member on_new_commit (value: Str)  = Yzl.str(value, "on_new_commit")
  static member on_job_failure (value: string)  = Yzl.str(value, "on_job_failure")
  static member on_job_failure (value: Str)  = Yzl.str(value, "on_job_failure")
  static member Default = workflowAutoCancel()
  static member yzl (build:NamedNode list) : Node = build |> lift
type workflowName() =
  static member Default = workflowName()
  static member yzl (build:NamedNode list) : Node = build |> lift
type includeRules() =
  static member Default = includeRules()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rules() =
  static member Default = rules()
  static member yzl (build:NamedNode list) : Node = build |> lift
type after_script() =
  static member Default = after_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type before_script() =
  static member Default = before_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type optional_script() =
  static member Default = optional_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type steps() =
  static member Default = steps()
  static member yzl (build:NamedNode list) : Node = build |> lift
type script() =
  static member Default = script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type secrets() =
  static member Default = secrets()
  static member yzl (build:NamedNode list) : Node = build |> lift
type identity() =
  static member Default = identity()
  static member yzl (build:NamedNode list) : Node = build |> lift
type id_tokens() =
  static member Default = id_tokens()
  static member yzl (build:NamedNode list) : Node = build |> lift
type services() =
  static member Default = services()
  static member yzl (build:NamedNode list) : Node = build |> lift
type image() =
  static member Default = image()
  static member yzl (build:NamedNode list) : Node = build |> lift
type reference() =
  static member Default = reference()
  static member yzl (build:NamedNode list) : Node = build |> lift
type include_item() =
  static member Default = include_item()
  static member yzl (build:NamedNode list) : Node = build |> lift
type jobInputs() =
  static member Default = jobInputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type configInputs() =
  static member Default = configInputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type baseInput() =
  static member ``default`` (value: Node)  = Yzl.named(value, "default")
  static member regex (value: string)  = Yzl.str(value, "regex")
  static member regex (value: Str)  = Yzl.str(value, "regex")
  static member options (value: Node list)  = Yzl.seq(value, "options")
  static member description (value: string)  = Yzl.str(value, "description")
  static member description (value: Str)  = Yzl.str(value, "description")
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member Default = baseInput()
  static member yzl (build:NamedNode list) : Node = build |> lift
type string_file_list() =
  static member Default = string_file_list()
  static member yzl (build:NamedNode list) : Node = build |> lift
type artifacts() =
  static member reports (value: NamedNode list)  = Yzl.map(value, "reports")
  static member expire_in (value: string)  = Yzl.str(value, "expire_in")
  static member expire_in (value: Str)  = Yzl.str(value, "expire_in")
  static member access (value: string)  = Yzl.str(value, "access")
  static member access (value: Str)  = Yzl.str(value, "access")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member expose_as (value: string)  = Yzl.str(value, "expose_as")
  static member expose_as (value: Str)  = Yzl.str(value, "expose_as")
  static member exclude (value: string list)  = Yzl.seq(value, "exclude")
  static member Default = artifacts()
  static member yzl (build:NamedNode list) : Node = build |> lift

[<AutoOpen>]
module Builders =
  let untracked value = Yzl.boolean(value, "untracked")
  let inline paths value = Yzl.seq(value, "paths")
  let inline work_dir value = Yzl.str(value, "work_dir")
  let inline command value = Yzl.seq(value, "command")
  let oci value = Yzl.map(value, "oci")
  let git value = Yzl.map(value, "git")
  let pre_get_sources_script value = Yzl.map(value, "pre_get_sources_script")
  let pages value = Yzl.named(value, "pages")
  let inline publish value = Yzl.str(value, "publish")
  let ``inherit`` value = Yzl.map(value, "inherit")
  let trigger value = Yzl.named(value, "trigger")
  let inline resource_group value = Yzl.str(value, "resource_group")
  let interruptible value = Yzl.map(value, "interruptible")
  let ``parallel`` value = Yzl.map(value, "parallel")
  let retry value = Yzl.map(value, "retry")
  let inline coverage value = Yzl.str(value, "coverage")
  let release value = Yzl.map(value, "release")
  let environment value = Yzl.named(value, "environment")
  let artifacts value = Yzl.map(value, "artifacts")
  let inline dependencies value = Yzl.seq(value, "dependencies")
  let inline manual_confirmation value = Yzl.str(value, "manual_confirmation")
  let start_in value = Yzl.map(value, "start_in")
  let timeout value = Yzl.map(value, "timeout")
  let allow_failure value = Yzl.map(value, "allow_failure")
  let tags value = Yzl.map(value, "tags")
  let except value = Yzl.map(value, "except")
  let inline needs value = Yzl.seq(value, "needs")
  let extends value = Yzl.named(value, "extends")
  let only value = Yzl.map(value, "only")
  let stage value = Yzl.named(value, "stage")
  let run value = Yzl.map(value, "run")
  let script value = Yzl.map(value, "script")
  let secrets value = Yzl.map(value, "secrets")
  let inputs value = Yzl.map(value, "inputs")
  let identity value = Yzl.map(value, "identity")
  let id_tokens value = Yzl.map(value, "id_tokens")
  let cache value = Yzl.map(value, "cache")
  let variables value = Yzl.map(value, "variables")
  let rules value = Yzl.map(value, "rules")
  let hooks value = Yzl.map(value, "hooks")
  let after_script value = Yzl.map(value, "after_script")
  let before_script value = Yzl.map(value, "before_script")
  let services value = Yzl.map(value, "services")
  let image value = Yzl.map(value, "image")
  let inline fallback_keys value = Yzl.seq(value, "fallback_keys")
  let unprotect value = Yzl.boolean(value, "unprotect")
  let inline policy value = Yzl.str(value, "policy")
  let key value = Yzl.named(value, "key")
  let inline on_new_commit value = Yzl.str(value, "on_new_commit")
  let inline on_job_failure value = Yzl.str(value, "on_job_failure")
  let ``default`` value = Yzl.named(value, "default")
  let inline regex value = Yzl.str(value, "regex")
  let inline options value = Yzl.seq(value, "options")
  let inline description value = Yzl.str(value, "description")
  let inline ``type`` value = Yzl.str(value, "type")
  let reports value = Yzl.map(value, "reports")
  let inline expire_in value = Yzl.str(value, "expire_in")
  let inline access value = Yzl.str(value, "access")
  let inline name value = Yzl.str(value, "name")
  let inline expose_as value = Yzl.str(value, "expose_as")
  let inline exclude value = Yzl.seq(value, "exclude")
