// Auto-generated by Yzl.Bindings.Gen - do not edit manually.
// Source schema: https://gitlab.com/gitlab-org/gitlab/-/raw/v18.9.0-ee/app/assets/javascripts/editor/schema/ci.json
namespace rec Yzl.Bindings.GitlabCi
open Yzl.Core

type stepExec() =
  /// WorkDir is the working directly in which `command` will be exec'ed.
  static member work_dir (value: string)  = Yzl.str(value, "work_dir")
  /// WorkDir is the working directly in which `command` will be exec'ed.
  static member work_dir (value: Str)  = Yzl.str(value, "work_dir")
  /// Command are the parameters to the system exec API. It does not invoke a shell.
  static member command (value: string list)  = Yzl.seq(value, "command")
  static member Default = stepExec()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// OCIReference is a reference to a step hosted in an OCI repository.
type stepOciReference() =
  static member oci (value: NamedNode list)  = Yzl.map(value, "oci")
  static member Default = stepOciReference()
  static member yzl (build:NamedNode list) : Node = build |> lift
type oci() =
  /// The name of the file that defines the step, defaults to step.yml.
  static member file (value: string)  = Yzl.str(value, "file")
  /// The name of the file that defines the step, defaults to step.yml.
  static member file (value: Str)  = Yzl.str(value, "file")
  /// A directory inside the OCI image where the step can be found.
  static member dir (value: string)  = Yzl.str(value, "dir")
  /// A directory inside the OCI image where the step can be found.
  static member dir (value: Str)  = Yzl.str(value, "dir")
  /// A pointer to the image manifest hosted in the OCI repository.
  static member tag (value: string)  = Yzl.str(value, "tag")
  /// A pointer to the image manifest hosted in the OCI repository.
  static member tag (value: Str)  = Yzl.str(value, "tag")
  /// A path within the registry containing related OCI images. Typically the namespace, project, and image name.
  static member repository (value: string)  = Yzl.str(value, "repository")
  /// A path within the registry containing related OCI images. Typically the namespace, project, and image name.
  static member repository (value: Str)  = Yzl.str(value, "repository")
  /// The <host>[:<port>] of the container registry server.
  static member registry (value: string)  = Yzl.str(value, "registry")
  /// The <host>[:<port>] of the container registry server.
  static member registry (value: Str)  = Yzl.str(value, "registry")
  static member Default = oci()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// GitReference is a reference to a step in a Git repository.
type stepGitReference() =
  static member git (value: NamedNode list)  = Yzl.map(value, "git")
  static member Default = stepGitReference()
  static member yzl (build:NamedNode list) : Node = build |> lift
type git() =
  static member file (value: string)  = Yzl.str(value, "file")
  static member file (value: Str)  = Yzl.str(value, "file")
  static member rev (value: string)  = Yzl.str(value, "rev")
  static member rev (value: Str)  = Yzl.str(value, "rev")
  static member dir (value: string)  = Yzl.str(value, "dir")
  static member dir (value: Str)  = Yzl.str(value, "dir")
  static member url (value: string)  = Yzl.str(value, "url")
  static member url (value: Str)  = Yzl.str(value, "url")
  static member Default = git()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepNamedValues() =
  static member Default = stepNamedValues()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepNamedStrings() =
  static member Default = stepNamedStrings()
  static member yzl (build:NamedNode list) : Node = build |> lift
type stepName() =
  static member Default = stepName()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Any of these step use cases are valid.
type step() =
  static member Default = step()
  static member yzl (build:NamedNode list) : Node = build |> lift
type hooks() =
  static member pre_get_sources_script (value: NamedNode list)  = Yzl.map(value, "pre_get_sources_script")
  static member Default = hooks()
  static member yzl (build:NamedNode list) : Node = build |> lift
type tags() =
  static member Default = tags()
  static member yzl (build:NamedNode list) : Node = build |> lift
type job_template() =
  static member pages (value: Node)  = Yzl.named(value, "pages")
  /// Deprecated. Use `pages.publish` instead. A path to a directory that contains the files to be published with Pages.
  static member publish (value: string)  = Yzl.str(value, "publish")
  /// Deprecated. Use `pages.publish` instead. A path to a directory that contains the files to be published with Pages.
  static member publish (value: Str)  = Yzl.str(value, "publish")
  static member ``inherit`` (value: NamedNode list)  = Yzl.map(value, "inherit")
  static member trigger (value: Node)  = Yzl.named(value, "trigger")
  /// Limit job concurrency. Can be used to ensure that the Runner will not run certain jobs simultaneously.
  static member resource_group (value: string)  = Yzl.str(value, "resource_group")
  /// Limit job concurrency. Can be used to ensure that the Runner will not run certain jobs simultaneously.
  static member resource_group (value: Str)  = Yzl.str(value, "resource_group")
  static member interruptible (value: NamedNode list)  = Yzl.map(value, "interruptible")
  static member ``parallel`` (value: NamedNode list)  = Yzl.map(value, "parallel")
  static member retry (value: NamedNode list)  = Yzl.map(value, "retry")
  /// Must be a regular expression, optionally but recommended to be quoted, and must be surrounded with '/'. Example: '/Code coverage: \d+\.\d+/'
  static member coverage (value: string)  = Yzl.str(value, "coverage")
  /// Must be a regular expression, optionally but recommended to be quoted, and must be surrounded with '/'. Example: '/Code coverage: \d+\.\d+/'
  static member coverage (value: Str)  = Yzl.str(value, "coverage")
  /// Indicates that the job creates a Release.
  static member release (value: NamedNode list)  = Yzl.map(value, "release")
  /// Used to associate environment metadata with a deploy. Environment can have a name and URL attached to it, and will be displayed under /environments under the project.
  static member environment (value: Node)  = Yzl.named(value, "environment")
  static member artifacts (value: NamedNode list)  = Yzl.map(value, "artifacts")
  /// Specify a list of job names from earlier stages from which artifacts should be loaded. By default, all previous artifacts are passed. Use an empty array to skip downloading artifacts.
  static member dependencies (value: string list)  = Yzl.seq(value, "dependencies")
  static member manual_confirmation (value: string)  = Yzl.str(value, "manual_confirmation")
  static member manual_confirmation (value: Str)  = Yzl.str(value, "manual_confirmation")
  static member start_in (value: NamedNode list)  = Yzl.map(value, "start_in")
  static member ``when`` (value: NamedNode list)  = Yzl.map(value, "when")
  static member timeout (value: NamedNode list)  = Yzl.map(value, "timeout")
  static member allow_failure (value: NamedNode list)  = Yzl.map(value, "allow_failure")
  static member tags (value: NamedNode list)  = Yzl.map(value, "tags")
  /// Job will run *except* for when these filtering options match.
  static member except (value: NamedNode list)  = Yzl.map(value, "except")
  /// The list of jobs in previous stages whose sole completion is needed to start the current job.
  static member needs (value: Node list)  = Yzl.named(value |> SeqNode, "needs")
  /// The name of one or more jobs to inherit configuration from.
  static member extends (value: Node)  = Yzl.named(value, "extends")
  /// Job will run *only* when these filtering options match.
  static member only (value: NamedNode list)  = Yzl.map(value, "only")
  /// Define what stage the job will run in.
  static member stage (value: Node)  = Yzl.named(value, "stage")
  static member run (value: NamedNode list)  = Yzl.map(value, "run")
  static member script (value: NamedNode list)  = Yzl.map(value, "script")
  static member secrets (value: NamedNode list)  = Yzl.map(value, "secrets")
  static member inputs (value: NamedNode list)  = Yzl.map(value, "inputs")
  static member identity (value: NamedNode list)  = Yzl.map(value, "identity")
  static member id_tokens (value: NamedNode list)  = Yzl.map(value, "id_tokens")
  static member cache (value: NamedNode list)  = Yzl.map(value, "cache")
  static member variables (value: NamedNode list)  = Yzl.map(value, "variables")
  static member rules (value: NamedNode list)  = Yzl.map(value, "rules")
  static member hooks (value: NamedNode list)  = Yzl.map(value, "hooks")
  static member after_script (value: NamedNode list)  = Yzl.map(value, "after_script")
  static member before_script (value: NamedNode list)  = Yzl.map(value, "before_script")
  static member services (value: NamedNode list)  = Yzl.map(value, "services")
  static member image (value: NamedNode list)  = Yzl.map(value, "image")
  static member Default = job_template()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ``inherit``() =
  static member variables (value: Node)  = Yzl.named(value, "variables")
  static member ``default`` (value: Node)  = Yzl.named(value, "default")
  static member Default = ``inherit``()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Indicates that the job creates a Release.
type release() =
  static member assets (value: NamedNode list)  = Yzl.map(value, "assets")
  /// The date and time when the release is ready. Defaults to the current date and time if not defined. Should be enclosed in quotes and expressed in ISO 8601 format.
  static member released_at (value: string)  = Yzl.str(value, "released_at")
  /// The date and time when the release is ready. Defaults to the current date and time if not defined. Should be enclosed in quotes and expressed in ISO 8601 format.
  static member released_at (value: Str)  = Yzl.str(value, "released_at")
  /// The title of each milestone the release is associated with.
  static member milestones (value: string list)  = Yzl.seq(value, "milestones")
  /// If the release: tag_name doesn’t exist yet, the release is created from ref. ref can be a commit SHA, another tag name, or a branch name.
  static member ref (value: string)  = Yzl.str(value, "ref")
  /// If the release: tag_name doesn’t exist yet, the release is created from ref. ref can be a commit SHA, another tag name, or a branch name.
  static member ref (value: Str)  = Yzl.str(value, "ref")
  /// The Release name. If omitted, it is populated with the value of release: tag_name.
  static member name (value: string)  = Yzl.str(value, "name")
  /// The Release name. If omitted, it is populated with the value of release: tag_name.
  static member name (value: Str)  = Yzl.str(value, "name")
  /// Specifies the longer description of the Release.
  static member description (value: string)  = Yzl.str(value, "description")
  /// Specifies the longer description of the Release.
  static member description (value: Str)  = Yzl.str(value, "description")
  /// Message to use if creating a new annotated tag.
  static member tag_message (value: string)  = Yzl.str(value, "tag_message")
  /// Message to use if creating a new annotated tag.
  static member tag_message (value: Str)  = Yzl.str(value, "tag_message")
  /// The tag_name must be specified. It can refer to an existing Git tag or can be specified by the user.
  static member tag_name (value: string)  = Yzl.str(value, "tag_name")
  /// The tag_name must be specified. It can refer to an existing Git tag or can be specified by the user.
  static member tag_name (value: Str)  = Yzl.str(value, "tag_name")
  static member Default = release()
  static member yzl (build:NamedNode list) : Node = build |> lift
type assets() =
  /// Include asset links in the release.
  static member links (value: NamedNode list list)  = Yzl.seq(value, "links")
  static member Default = assets()
  static member yzl (build:NamedNode list) : Node = build |> lift
type job() =
  static member Default = job()
  static member yzl (build:NamedNode list) : Node = build |> lift
type inputs() =
  static member Default = inputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type interruptible() =
  static member Default = interruptible()
  static member yzl (build:NamedNode list) : Node = build |> lift
type retry_errors() =
  static member Default = retry_errors()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// The number of times the job will be retried if it fails. Defaults to 0 and can max be retried 2 times (3 times total).
type retry_max() =
  static member Default = retry_max()
  static member yzl (build:NamedNode list) : Node = build |> lift
type retry() =
  static member Default = retry()
  static member yzl (build:NamedNode list) : Node = build |> lift
type filter() =
  static member Default = filter()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Filter job by different keywords that determine origin or state, or by supplying string/regex to check against branch/tag names.
type filter_refs() =
  static member Default = filter_refs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type cache_item() =
  static member fallback_keys (value: string list)  = Yzl.seq(value, "fallback_keys")
  static member ``when`` (value: string)  = Yzl.str(value, "when")
  static member ``when`` (value: Str)  = Yzl.str(value, "when")
  static member untracked (value: bool)  = Yzl.boolean(value, "untracked")
  static member unprotect (value: bool)  = Yzl.boolean(value, "unprotect")
  static member policy (value: string)  = Yzl.str(value, "policy")
  static member policy (value: Str)  = Yzl.str(value, "policy")
  static member paths (value: string list)  = Yzl.seq(value, "paths")
  static member key (value: Node)  = Yzl.named(value, "key")
  static member Default = cache_item()
  static member yzl (build:NamedNode list) : Node = build |> lift
type cache() =
  static member Default = cache()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ``when``() =
  static member Default = ``when``()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Use the `needs:parallel:matrix` keyword to specify parallelized jobs needed to be completed for the job to run. [Learn More](https://docs.gitlab.com/ci/yaml/#needsparallelmatrix)
type parallel_matrix() =
  static member Default = parallel_matrix()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Splits up a single job into multiple that run in parallel. Provides `CI_NODE_INDEX` and `CI_NODE_TOTAL` environment variables to the jobs.
type ``parallel``() =
  static member Default = ``parallel``()
  static member yzl (build:NamedNode list) : Node = build |> lift
type allow_failure() =
  static member Default = allow_failure()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rulesNeeds() =
  static member Default = rulesNeeds()
  static member yzl (build:NamedNode list) : Node = build |> lift
type start_in() =
  static member Default = start_in()
  static member yzl (build:NamedNode list) : Node = build |> lift
type timeout() =
  static member Default = timeout()
  static member yzl (build:NamedNode list) : Node = build |> lift
type exists() =
  static member Default = exists()
  static member yzl (build:NamedNode list) : Node = build |> lift
type changes() =
  static member Default = changes()
  static member yzl (build:NamedNode list) : Node = build |> lift
type ``if``() =
  static member Default = ``if``()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rulesVariables() =
  static member Default = rulesVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
type jobVariables() =
  static member Default = jobVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
type globalVariables() =
  static member Default = globalVariables()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Define the rules for when pipeline should be automatically cancelled.
type workflowAutoCancel() =
  static member on_new_commit (value: string)  = Yzl.str(value, "on_new_commit")
  static member on_new_commit (value: Str)  = Yzl.str(value, "on_new_commit")
  static member on_job_failure (value: string)  = Yzl.str(value, "on_job_failure")
  static member on_job_failure (value: Str)  = Yzl.str(value, "on_job_failure")
  static member Default = workflowAutoCancel()
  static member yzl (build:NamedNode list) : Node = build |> lift
type workflowName() =
  static member Default = workflowName()
  static member yzl (build:NamedNode list) : Node = build |> lift
type includeRules() =
  static member Default = includeRules()
  static member yzl (build:NamedNode list) : Node = build |> lift
type rules() =
  static member Default = rules()
  static member yzl (build:NamedNode list) : Node = build |> lift
type after_script() =
  static member Default = after_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type before_script() =
  static member Default = before_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type optional_script() =
  static member Default = optional_script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type steps() =
  static member Default = steps()
  static member yzl (build:NamedNode list) : Node = build |> lift
type script() =
  static member Default = script()
  static member yzl (build:NamedNode list) : Node = build |> lift
type secrets() =
  static member Default = secrets()
  static member yzl (build:NamedNode list) : Node = build |> lift
type identity() =
  static member Default = identity()
  static member yzl (build:NamedNode list) : Node = build |> lift
type id_tokens() =
  static member Default = id_tokens()
  static member yzl (build:NamedNode list) : Node = build |> lift
type services() =
  static member Default = services()
  static member yzl (build:NamedNode list) : Node = build |> lift
type image() =
  static member Default = image()
  static member yzl (build:NamedNode list) : Node = build |> lift
type reference() =
  static member Default = reference()
  static member yzl (build:NamedNode list) : Node = build |> lift
type include_item() =
  static member Default = include_item()
  static member yzl (build:NamedNode list) : Node = build |> lift
type jobInputs() =
  static member Default = jobInputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type configInputs() =
  static member Default = configInputs()
  static member yzl (build:NamedNode list) : Node = build |> lift
type baseInput() =
  static member ``default`` (value: Node)  = Yzl.named(value, "default")
  static member regex (value: string)  = Yzl.str(value, "regex")
  static member regex (value: Str)  = Yzl.str(value, "regex")
  static member options (value: Node list)  = Yzl.named(value |> SeqNode, "options")
  static member description (value: string)  = Yzl.str(value, "description")
  static member description (value: Str)  = Yzl.str(value, "description")
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member Default = baseInput()
  static member yzl (build:NamedNode list) : Node = build |> lift
type string_file_list() =
  static member Default = string_file_list()
  static member yzl (build:NamedNode list) : Node = build |> lift
type artifacts() =
  static member reports (value: NamedNode list)  = Yzl.map(value, "reports")
  static member expire_in (value: string)  = Yzl.str(value, "expire_in")
  static member expire_in (value: Str)  = Yzl.str(value, "expire_in")
  static member access (value: string)  = Yzl.str(value, "access")
  static member access (value: Str)  = Yzl.str(value, "access")
  static member ``when`` (value: string)  = Yzl.str(value, "when")
  static member ``when`` (value: Str)  = Yzl.str(value, "when")
  static member untracked (value: bool)  = Yzl.boolean(value, "untracked")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member expose_as (value: string)  = Yzl.str(value, "expose_as")
  static member expose_as (value: Str)  = Yzl.str(value, "expose_as")
  static member exclude (value: string list)  = Yzl.seq(value, "exclude")
  static member paths (value: string list)  = Yzl.seq(value, "paths")
  static member Default = artifacts()
  static member yzl (build:NamedNode list) : Node = build |> lift
type reports() =
  /// Path to file or list of files with Repository X-Ray report(s).
  static member repository_xray (value: NamedNode list)  = Yzl.map(value, "repository_xray")
  static member load_performance (value: NamedNode list)  = Yzl.map(value, "load_performance")
  static member cyclonedx (value: NamedNode list)  = Yzl.map(value, "cyclonedx")
  /// Path to file or list of files with terraform plan(s).
  static member terraform (value: NamedNode list)  = Yzl.map(value, "terraform")
  /// Path to file or list of files with custom metrics report(s).
  static member metrics (value: NamedNode list)  = Yzl.map(value, "metrics")
  /// Path to file or list of files with secret detection report(s).
  static member secret_detection (value: NamedNode list)  = Yzl.map(value, "secret_detection")
  /// Path to file or list of files with requirements report(s).
  static member requirements (value: NamedNode list)  = Yzl.map(value, "requirements")
  /// Path to file or list of files with license report(s).
  static member license_scanning (value: NamedNode list)  = Yzl.map(value, "license_scanning")
  /// Deprecated in 12.8: Path to file or list of files with license report(s).
  static member license_management (value: NamedNode list)  = Yzl.map(value, "license_management")
  /// Path to file or list of files with DAST vulnerabilities report(s).
  static member dast (value: NamedNode list)  = Yzl.map(value, "dast")
  /// Path to file or list of files with Container scanning vulnerabilities report(s).
  static member container_scanning (value: NamedNode list)  = Yzl.map(value, "container_scanning")
  /// Path to file or list of files with Dependency scanning vulnerabilities report(s).
  static member dependency_scanning (value: NamedNode list)  = Yzl.map(value, "dependency_scanning")
  /// Path to file or list of files with SAST vulnerabilities report(s).
  static member sast (value: NamedNode list)  = Yzl.map(value, "sast")
  /// Path to file or list of files containing code intelligence (Language Server Index Format).
  static member lsif (value: NamedNode list)  = Yzl.map(value, "lsif")
  /// Path to file or list of files containing runtime-created variables for this job.
  static member dotenv (value: NamedNode list)  = Yzl.map(value, "dotenv")
  /// Path to file or list of files with code quality report(s) (such as Code Climate).
  static member codequality (value: NamedNode list)  = Yzl.map(value, "codequality")
  /// Used to collect coverage reports from the job.
  static member coverage_report (value: NamedNode list)  = Yzl.map(value, "coverage_report")
  /// Path to a single file with browser performance metric report(s).
  static member browser_performance (value: string)  = Yzl.str(value, "browser_performance")
  /// Path to a single file with browser performance metric report(s).
  static member browser_performance (value: Str)  = Yzl.str(value, "browser_performance")
  /// Path for file(s) that should be parsed as JUnit XML result
  static member junit (value: Node)  = Yzl.named(value, "junit")
  /// Path to JSON file with annotations report.
  static member annotations (value: string)  = Yzl.str(value, "annotations")
  /// Path to JSON file with annotations report.
  static member annotations (value: Str)  = Yzl.str(value, "annotations")
  /// Path to JSON file with accessibility report.
  static member accessibility (value: string)  = Yzl.str(value, "accessibility")
  /// Path to JSON file with accessibility report.
  static member accessibility (value: Str)  = Yzl.str(value, "accessibility")
  static member Default = reports()
  static member yzl (build:NamedNode list) : Node = build |> lift
/// Used to collect coverage reports from the job.
type coverage_report() =
  /// Path to the coverage report file that should be parsed.
  static member path (value: string)  = Yzl.str(value, "path")
  /// Path to the coverage report file that should be parsed.
  static member path (value: Str)  = Yzl.str(value, "path")
  /// Code coverage format used by the test framework.
  static member coverage_format (value: string)  = Yzl.str(value, "coverage_format")
  static member Default = coverage_report()
  static member yzl (build:NamedNode list) : Node = build |> lift

type Builders() =
  static member work_dir (value: string)  = Yzl.str(value, "work_dir")
  static member work_dir (value: Str)  = Yzl.str(value, "work_dir")
  static member command (value: string list)  = Yzl.seq(value, "command")
  static member oci (value: NamedNode list)  = Yzl.map(value, "oci")
  static member file (value: string)  = Yzl.str(value, "file")
  static member file (value: Str)  = Yzl.str(value, "file")
  static member dir (value: string)  = Yzl.str(value, "dir")
  static member dir (value: Str)  = Yzl.str(value, "dir")
  static member tag (value: string)  = Yzl.str(value, "tag")
  static member tag (value: Str)  = Yzl.str(value, "tag")
  static member repository (value: string)  = Yzl.str(value, "repository")
  static member repository (value: Str)  = Yzl.str(value, "repository")
  static member registry (value: string)  = Yzl.str(value, "registry")
  static member registry (value: Str)  = Yzl.str(value, "registry")
  static member git (value: NamedNode list)  = Yzl.map(value, "git")
  static member rev (value: string)  = Yzl.str(value, "rev")
  static member rev (value: Str)  = Yzl.str(value, "rev")
  static member url (value: string)  = Yzl.str(value, "url")
  static member url (value: Str)  = Yzl.str(value, "url")
  static member pre_get_sources_script (value: NamedNode list)  = Yzl.map(value, "pre_get_sources_script")
  static member pages (value: Node)  = Yzl.named(value, "pages")
  static member publish (value: string)  = Yzl.str(value, "publish")
  static member publish (value: Str)  = Yzl.str(value, "publish")
  static member ``inherit`` (value: NamedNode list)  = Yzl.map(value, "inherit")
  static member trigger (value: Node)  = Yzl.named(value, "trigger")
  static member resource_group (value: string)  = Yzl.str(value, "resource_group")
  static member resource_group (value: Str)  = Yzl.str(value, "resource_group")
  static member interruptible (value: NamedNode list)  = Yzl.map(value, "interruptible")
  static member ``parallel`` (value: NamedNode list)  = Yzl.map(value, "parallel")
  static member retry (value: NamedNode list)  = Yzl.map(value, "retry")
  static member coverage (value: string)  = Yzl.str(value, "coverage")
  static member coverage (value: Str)  = Yzl.str(value, "coverage")
  static member release (value: NamedNode list)  = Yzl.map(value, "release")
  static member environment (value: Node)  = Yzl.named(value, "environment")
  static member artifacts (value: NamedNode list)  = Yzl.map(value, "artifacts")
  static member dependencies (value: string list)  = Yzl.seq(value, "dependencies")
  static member manual_confirmation (value: string)  = Yzl.str(value, "manual_confirmation")
  static member manual_confirmation (value: Str)  = Yzl.str(value, "manual_confirmation")
  static member start_in (value: NamedNode list)  = Yzl.map(value, "start_in")
  static member ``when`` (value: NamedNode list)  = Yzl.map(value, "when")
  static member timeout (value: NamedNode list)  = Yzl.map(value, "timeout")
  static member allow_failure (value: NamedNode list)  = Yzl.map(value, "allow_failure")
  static member tags (value: NamedNode list)  = Yzl.map(value, "tags")
  static member except (value: NamedNode list)  = Yzl.map(value, "except")
  static member needs (value: Node list)  = Yzl.named(value |> SeqNode, "needs")
  static member extends (value: Node)  = Yzl.named(value, "extends")
  static member only (value: NamedNode list)  = Yzl.map(value, "only")
  static member stage (value: Node)  = Yzl.named(value, "stage")
  static member run (value: NamedNode list)  = Yzl.map(value, "run")
  static member script (value: NamedNode list)  = Yzl.map(value, "script")
  static member secrets (value: NamedNode list)  = Yzl.map(value, "secrets")
  static member inputs (value: NamedNode list)  = Yzl.map(value, "inputs")
  static member identity (value: NamedNode list)  = Yzl.map(value, "identity")
  static member id_tokens (value: NamedNode list)  = Yzl.map(value, "id_tokens")
  static member cache (value: NamedNode list)  = Yzl.map(value, "cache")
  static member variables (value: NamedNode list)  = Yzl.map(value, "variables")
  static member rules (value: NamedNode list)  = Yzl.map(value, "rules")
  static member hooks (value: NamedNode list)  = Yzl.map(value, "hooks")
  static member after_script (value: NamedNode list)  = Yzl.map(value, "after_script")
  static member before_script (value: NamedNode list)  = Yzl.map(value, "before_script")
  static member services (value: NamedNode list)  = Yzl.map(value, "services")
  static member image (value: NamedNode list)  = Yzl.map(value, "image")
  static member variables (value: Node)  = Yzl.named(value, "variables")
  static member ``default`` (value: Node)  = Yzl.named(value, "default")
  static member assets (value: NamedNode list)  = Yzl.map(value, "assets")
  static member released_at (value: string)  = Yzl.str(value, "released_at")
  static member released_at (value: Str)  = Yzl.str(value, "released_at")
  static member milestones (value: string list)  = Yzl.seq(value, "milestones")
  static member ref (value: string)  = Yzl.str(value, "ref")
  static member ref (value: Str)  = Yzl.str(value, "ref")
  static member name (value: string)  = Yzl.str(value, "name")
  static member name (value: Str)  = Yzl.str(value, "name")
  static member description (value: string)  = Yzl.str(value, "description")
  static member description (value: Str)  = Yzl.str(value, "description")
  static member tag_message (value: string)  = Yzl.str(value, "tag_message")
  static member tag_message (value: Str)  = Yzl.str(value, "tag_message")
  static member tag_name (value: string)  = Yzl.str(value, "tag_name")
  static member tag_name (value: Str)  = Yzl.str(value, "tag_name")
  static member links (value: NamedNode list list)  = Yzl.seq(value, "links")
  static member fallback_keys (value: string list)  = Yzl.seq(value, "fallback_keys")
  static member ``when`` (value: string)  = Yzl.str(value, "when")
  static member ``when`` (value: Str)  = Yzl.str(value, "when")
  static member untracked (value: bool)  = Yzl.boolean(value, "untracked")
  static member unprotect (value: bool)  = Yzl.boolean(value, "unprotect")
  static member policy (value: string)  = Yzl.str(value, "policy")
  static member policy (value: Str)  = Yzl.str(value, "policy")
  static member paths (value: string list)  = Yzl.seq(value, "paths")
  static member key (value: Node)  = Yzl.named(value, "key")
  static member on_new_commit (value: string)  = Yzl.str(value, "on_new_commit")
  static member on_new_commit (value: Str)  = Yzl.str(value, "on_new_commit")
  static member on_job_failure (value: string)  = Yzl.str(value, "on_job_failure")
  static member on_job_failure (value: Str)  = Yzl.str(value, "on_job_failure")
  static member regex (value: string)  = Yzl.str(value, "regex")
  static member regex (value: Str)  = Yzl.str(value, "regex")
  static member options (value: Node list)  = Yzl.named(value |> SeqNode, "options")
  static member ``type`` (value: string)  = Yzl.str(value, "type")
  static member ``type`` (value: Str)  = Yzl.str(value, "type")
  static member reports (value: NamedNode list)  = Yzl.map(value, "reports")
  static member expire_in (value: string)  = Yzl.str(value, "expire_in")
  static member expire_in (value: Str)  = Yzl.str(value, "expire_in")
  static member access (value: string)  = Yzl.str(value, "access")
  static member access (value: Str)  = Yzl.str(value, "access")
  static member expose_as (value: string)  = Yzl.str(value, "expose_as")
  static member expose_as (value: Str)  = Yzl.str(value, "expose_as")
  static member exclude (value: string list)  = Yzl.seq(value, "exclude")
  static member repository_xray (value: NamedNode list)  = Yzl.map(value, "repository_xray")
  static member load_performance (value: NamedNode list)  = Yzl.map(value, "load_performance")
  static member cyclonedx (value: NamedNode list)  = Yzl.map(value, "cyclonedx")
  static member terraform (value: NamedNode list)  = Yzl.map(value, "terraform")
  static member metrics (value: NamedNode list)  = Yzl.map(value, "metrics")
  static member secret_detection (value: NamedNode list)  = Yzl.map(value, "secret_detection")
  static member requirements (value: NamedNode list)  = Yzl.map(value, "requirements")
  static member license_scanning (value: NamedNode list)  = Yzl.map(value, "license_scanning")
  static member license_management (value: NamedNode list)  = Yzl.map(value, "license_management")
  static member dast (value: NamedNode list)  = Yzl.map(value, "dast")
  static member container_scanning (value: NamedNode list)  = Yzl.map(value, "container_scanning")
  static member dependency_scanning (value: NamedNode list)  = Yzl.map(value, "dependency_scanning")
  static member sast (value: NamedNode list)  = Yzl.map(value, "sast")
  static member lsif (value: NamedNode list)  = Yzl.map(value, "lsif")
  static member dotenv (value: NamedNode list)  = Yzl.map(value, "dotenv")
  static member codequality (value: NamedNode list)  = Yzl.map(value, "codequality")
  static member coverage_report (value: NamedNode list)  = Yzl.map(value, "coverage_report")
  static member browser_performance (value: string)  = Yzl.str(value, "browser_performance")
  static member browser_performance (value: Str)  = Yzl.str(value, "browser_performance")
  static member junit (value: Node)  = Yzl.named(value, "junit")
  static member annotations (value: string)  = Yzl.str(value, "annotations")
  static member annotations (value: Str)  = Yzl.str(value, "annotations")
  static member accessibility (value: string)  = Yzl.str(value, "accessibility")
  static member accessibility (value: Str)  = Yzl.str(value, "accessibility")
  static member path (value: string)  = Yzl.str(value, "path")
  static member path (value: Str)  = Yzl.str(value, "path")
  static member coverage_format (value: string)  = Yzl.str(value, "coverage_format")
